### ISSUE TITLE
How exactly do you use this package to obtain the token key and token secret?

### ISSUE THREAD

**Issue by crzzano** [codegreencreative/laravel-aweber#1]

**Comment by TheDudeV2** [comment]
I'm encountering this same issue. Is this perhaps related to recent changes in the Aweber API?

**Comment by upwebdesign** [comment]
You need to get your own `AWEBER_TOKEN_KEY ` and `AWEBER_TOKEN_SECRET ` from Aweber. I hope this article helps:

https://help.aweber.com/hc/en-us/articles/360007147994-How-do-I-use-OAuth-1-authentication-with-AWeber-s-API-

**Comment by vicsystems55** [comment]
i really wish i had another option, the process is boggling tedious.

**Comment by vicsystems55** [comment]
Error
Interface "CodeGreenCreative\Aweber\Contracts\AweberApiContract" not found

**Comment by upwebdesign** [comment]
@vicsystems55 I know the issue you had presented has been around for a while, but I just had a chance to go and clean up this package a bit including adding the ability to connect to consumer accounts. I just released a new version of the package if you are still interested.
